tap "getsentry/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "psykube/tap"
tap "wix/brew"
brew "ack"
brew "antibody"
brew "antigen"
brew "asciidoctor"
brew "readline"
brew "autoconf"
brew "gdbm"
brew "openssl@1.1"
brew "xz"
brew "autojump"
brew "automake"
brew "aws-shell"
brew "bdw-gc"
brew "bison"
brew "carthage"
brew "certbot"
brew "libtool"
brew "cfssl"
brew "chruby"
brew "cli53"
brew "cmake"
brew "gmp"
brew "coreutils"
brew "libyaml"
brew "go"
brew "direnv"
brew "docker", link: false
brew "docker-compose"
brew "docker-credential-helper"
brew "docker-machine", link: false
brew "doxygen"
brew "erlang"
brew "elixir"
brew "fop"
brew "fswatch"
brew "gettext"
brew "git"
brew "glew"
brew "libffi"
brew "grep"
brew "helm"
brew "htop"
brew "hub"
brew "imagemagick"
brew "ipfs"
brew "oniguruma"
brew "jq"
brew "kubernetes-cli"
brew "libev"
brew "libssh2"
brew "libgit2"
brew "libgsf"
brew "llvm"
brew "mas"
brew "nim"
brew "nvm"
brew "pandoc"
brew "peco"
brew "postgresql"
brew "ruby-install"
brew "rust"
brew "sdl2"
brew "shellcheck"
brew "starship"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "travis"
brew "watch"
brew "watchman"
brew "wget"
brew "zsh-completions"
brew "getsentry/tools/sentry-cli"
brew "psykube/tap/psykube"
cask "android-platform-tools"
cask "android-sdk"
cask "android-studio"
cask "appium"
cask "authy"
cask "charles"
cask "docker"
cask "dropbox"
cask "elgato-stream-deck"
cask "firefox"
cask "font-hack"
cask "font-jetbrains-mono"
cask "gas-mask"
cask "gitter"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-drive-file-stream"
cask "gpg-suite"
cask "graphql-playground"
cask "iterm2"
cask "kaleidoscope"
cask "keybase"
cask "kitematic"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "moom"
cask "navicat-for-postgresql"
cask "nimbus"
cask "react-native-debugger"
cask "rescuetime"
cask "sketch"
cask "slack"
cask "spotify"
cask "tower"
cask "visual-studio-code"
cask "vnc-viewer"
cask "wine-stable"
cask "xquartz"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "DaisyDisk", id: 411643860
mas "GarageBand", id: 682658836
mas "Hidden Bar", id: 1452453066
mas "iMovie", id: 408981434
mas "iNet Network Scanner", id: 403304796
mas "iStatistica Pro", id: 1447778660
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Moom", id: 419330170
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Remote Desktop", id: 409907375
mas "TheOregonTrail", id: 1502228492
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835
