tap "amberframework/amber"
tap "garethr/kubeval"
tap "getantibody/tap"
tap "getsentry/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jwaldrip/on-tap"
tap "psykube/tap"
tap "wix/brew"
cask "java"
cask "xquartz"
brew "ack"
brew "antigen"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl"
brew "readline"
brew "asdf"
brew "autojump"
brew "gdbm"
brew "xz"
brew "aws-shell"
brew "bdw-gc"
brew "bison"
brew "camlp4"
brew "certbot"
brew "cfssl"
brew "chruby"
brew "cli53"
brew "cmake"
brew "gmp"
brew "libffi"
brew "llvm@6"
brew "crystal"
brew "dmd"
brew "docker", link: false
brew "docker-credential-helper"
brew "docker-machine", link: false
brew "docker-machine-driver-xhyve"
brew "doxygen"
brew "gettext"
brew "erlang"
brew "elixir"
brew "sdl2"
brew "ffmpeg"
brew "fop"
brew "fswatch"
brew "git"
brew "git-lfs"
brew "glew"
brew "go"
brew "gource"
brew "grep"
brew "htop"
brew "hub"
brew "imagemagick"
brew "ipfs"
brew "oniguruma"
brew "jq"
brew "kubernetes-cli"
brew "libev"
brew "libssh2"
brew "libgit2"
brew "libgsf"
brew "llvm"
brew "llvm@5"
brew "mas"
brew "pkg-config"
brew "msitools"
brew "nim"
brew "nvm"
brew "peco"
brew "ruby-install"
brew "rust"
brew "shellcheck"
brew "telnet"
brew "terraform"
brew "the_silver_searcher"
brew "travis"
brew "unrar"
brew "watch"
brew "watchman"
brew "wget"
brew "woff2"
brew "zsh-completions"
brew "amberframework/amber/amber"
brew "garethr/kubeval/kubeval"
brew "getantibody/tap/antibody"
brew "getsentry/tools/sentry-cli"
brew "jwaldrip/on-tap/fastpass", args: ["HEAD"]
brew "psykube/tap/psykube"
brew "wix/brew/applesimutils"
cask "android-platform-tools"
cask "android-sdk"
cask "android-studio"
cask "appium"
cask "authy"
cask "charles"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-hack"
cask "gas-mask"
cask "gitter"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "graphql-playground"
cask "intel-haxm"
cask "iterm2"
cask "java8"
cask "joinme"
cask "kaleidoscope"
cask "keybase"
cask "kitematic"
cask "microsoft-office"
cask "moom"
cask "nimbus"
cask "react-native-debugger"
cask "rescuetime"
cask "sketch"
cask "slack"
cask "spotify"
cask "tower"
cask "visual-studio-code"
cask "vnc-viewer"
cask "wine-stable"
cask "zoomus"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Color Picker", id: 502401013
mas "DaisyDisk", id: 411643860
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iNet Network Scanner", id: 403304796
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Moom", id: 419330170
mas "Moom", id: 419330170
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Remote Desktop", id: 409907375
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835
