#! /bin/bash
set -e

# Remove Key Dirs
rm -rf ./.git
rm -rf ./.gitconfig
rm -rf ./.private

# Init
git init
git remote add origin https://github.com/jwaldrip/dotfiles.git
git fetch
git reset --hard origin/master
./setup
